/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testndk_JniClient */

#ifndef _Included_com_android_camera_util_DvdCtrl
#define _Included_com_android_camera_util_DvdCtrl
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_example_testndk_JniClient
 * Method:    StartPause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_camera_util_DvdCtrl_StartPause
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_testndk_JniClient_Pre
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_testndk_JniClient_Next
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_testndk_JniClient_Repeat
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_testndk_JniClient_Repeat
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_testndk_JniClient_SetVol
  (JNIEnv *, jclass, jint);

JNIEXPORT jint JNICALL Java_com_example_testndk_JniClient_Menu
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
